monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: heroku
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        heroku:
            type: stream
            path: "php://stderr"
            level: debug
